### ISSUE TITLE
Colors for form elements on modal

### ISSUE THREAD

**Issue by dliefbroer** [akveo/blur-admin#236]
As mentioned in a comment on #62 
When placing a form on a modal all form elements have white text on white background.

Same for icons on the inputs, white borders and white icons on a white background.

Maybe it's easier to implement a background on a modal?

**Comment by solenovex** [comment]
It would be great if you great guys can give an instruction on this, or I can change the color on modal, but I'm not sure if I can do this in the right way.

**Comment by adonespitogo** [comment]
I'll just share my work around on this

`src/sass/app/_form_in_modal.scss`
```scss
.modal {
  .modal-content {

    label, .help-block {
      color: $dropdown-text;
    }

    .has-success {
      input, textarea, select {
        border-color: $success;
      }

      label, .help-block {
        color: $success;
      }
    }

    .has-warning {
      input, textarea, select {
        border-color: $warning;
      }

      label, .help-block {
        color: $warning;
      }
    }

    .has-error {
      input, textarea, select {
        border-color: $danger;
      }

      label, .help-block {
        color: $danger;
      }
    }
  }
}
```
